import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import MainKonten from "./helpers/MainKonten";

const Nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${Nunito.className} cust-outer-container bg-[#FAFAFA] text-custBlack flex overflow-y-auto`}>
        <MainKonten>
          {children}
        </MainKonten>        
      </body>
    </html>
  );
}
